### ISSUE TITLE
How to deeply parse ontologies in simpleWebMatcher by OWLAPI

### ISSUE THREAD

**Issue by liweizhuo001** [dwslab/melt#102]
For MatcherYAAAOwlApi extends MatcherYAAA implements IMatcher<OWLOntology, Alignment, Properties>

I want to obtain the disjoint classes of given class, but my orignal code can not work.

```
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology onto = manager.loadOntologyFromOntologyDocument(file); 
OWLClass c : onto.getClassesInSignature();
{
     Set<OWLClassExpression> disjoints=c.getDisjointClasses(onto);  
}
```

//The warning: **The method getDisjointClasses(OWLOntology) is undefined for the type OWLClass**

If I want to obtain the domain or range of given objectpropertyies or dataproperties. This orignal code can not support.
```
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology onto = manager.loadOntologyFromOntologyDocument(file); 

OWLObjectProperty op : onto.getObjectPropertiesInSignature()
{
    Set<OWLClassExpression> Domain= op.getDomains(onto);
    Set<OWLClassExpression> Range= op.getRanges(onto);
}
```

**The method getDomains(OWLOntology) is undefined for the type OWLObjectProperty
The method getRanges(OWLOntology) is undefined for the type OWLObjectProperty**

The problem is similar to the dataproperties.

Does the pom.xml contain the complete OWLAPI in this  simpleWebMatcher project?  or the above methods have been changed in new OWLAPI?

Please tell me the reason, because these source codes asserted in [OWLAPI_tools.java](https://github.com/liweizhuo001/GMap1.1/blob/master/src/Tools/OWLAPI_tools.java) can be successfully  run in my Matcher.

**Comment by liweizhuo001** [comment]
```
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology onto = manager.loadOntologyFromOntologyDocument(file); 
OWLClass c : onto.getClassesInSignature();
{
    Set<OWLAnnotationProperty> annos = c.getAnnotationPropertiesInSignature();
}
```
**c. getAnnotationPropertiesInSignature() can not be used, which can obtain the labels or comments of the given class.**

**Comment by janothan** [comment]
Hi @liweizhuo001, 

it is hard to reproduce your problem. Which version of the OWL API do you require? MELT uses a rather recent version.
 
In case the problem is rooted merely in the OWL API version, you can just add your required version to the `pom.xml` such as:

```
<dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-distribution</artifactId>
            <version>5.1.9</version>
</dependency>
```

Do you mind sharing your project with us so that we can have a quick look in case the proposed solution does not work for you?

Best regards,
Jan

**Comment by liweizhuo001** [comment]
Thank you. I have try to add this dependency in pom.xml, but it does not work. 

Besides, we add some exteral lib such as org.semanticweb.elk.jar and HermiT_1.3.6.jar. Both of them are not helpful. I guess the methods may conflict with the existing packages. Because some of methods in my define class **OWLAPI_tools.java** can be worked.

The modifies project based on your simpleWebMatcher project is
https://drive.google.com/file/d/1qNhaNaj9KySbztwgBhqmhNentEQN83l5/view?usp=sharing

My defined class **OWLAPI_tools.java** in **Tools package** for parsing ontologies can not work in presented environment.

If **MatcherBridge.java in Action package** can run successfully in this maven project, then the file called **GMap_MELT_OWLAPI.java in de.uni_mannheim.informatik.dws.melt.demomatcher package** can be tested.

```
package de.uni_mannheim.informatik.dws.melt.demomatcher;

import java.net.URL;
import java.util.ArrayList;
import java.util.Properties;

import org.semanticweb.owlapi.model.OWLOntology;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import Actions.GMap_D;
import de.uni_mannheim.informatik.dws.melt.matching_owlapi.MatcherYAAAOwlApi;
import de.uni_mannheim.informatik.dws.melt.yet_another_alignment_api.Alignment;
import de.uni_mannheim.informatik.dws.melt.yet_another_alignment_api.CorrespondenceRelation;
public class GMap_MELT_OWLAPI extends MatcherYAAAOwlApi {  
	private static final Logger LOGGER = LoggerFactory.getLogger(GMap_MELT_OWLAPI.class);
	public GMap_D gmap;
	public ArrayList<String> mappings;
		
	public Alignment match(URL source, URL target, Alignment inputAlignment, Properties properties) throws Exception 	
	{
		Alignment alignment = new Alignment();
		try {			
			gmap  =new GMap_D();			
			gmap.init(source, target);
										
			LOGGER.info("Matching with GMap completed");
									
			URL url_alignment=gmap.returnAlignmentFile();			
			mappings=gmap.GetAligenmt();			
			for(String s:mappings)
			{
				System.out.println(s);
				String parts[]=s.split(",");
				
				alignment.add(parts[0],parts[1],Double.parseDouble(parts[3]),CorrespondenceRelation.EQUIVALENCE);				
			}						
		}
		catch (Exception e){
			LOGGER.error("Error matching with GMap");
			LOGGER.error(e.getLocalizedMessage());
		}
		
		return alignment;
	}
	
	public Alignment match(OWLOntology source, OWLOntology target, Alignment inputAlignment, Properties p)
			throws Exception {
		Alignment alignment = new Alignment();	
		try {						
			LOGGER.info("Matching with GMap completed");
			mappings=gmap.GetAligenmt();			
			for(String s:mappings)
			{
				System.out.println(s);
				String parts[]=s.split(",");
				
				alignment.add(parts[0],parts[1],Double.parseDouble(parts[3]),CorrespondenceRelation.EQUIVALENCE);				
			}			
		}			
			catch (Exception e){
				LOGGER.error("Error matching with GMap");
				LOGGER.error(e.getLocalizedMessage());
			}
			
		return alignment;	
	}

}
```

My original project is https://github.com/liweizhuo001/GMap1.1, which has finished three tracks in OAEI 2015. Although it is not a maven project and its code is so coarse, I believe that its inputs and outputs are very friendly for most users. 

Besides, I hope that MatcherYAAAOwlApi.java could support more parse ways such as supporting local paths or URLs of ontologies.

**Comment by sven-h** [comment]
Hi @liweizhuo001 ,

the methods in OWLAPI changed over time (since 2015). Thus your code does not work with a new version of OWLAPI which MELT actually uses. But as Jan already mentioned, you can change the version to the one you like.
This has really nothing to do with MELT but with your code and further developments in OWLAPI.

I checked your code and searched for the version of OWLAPI which works with your code:
```
<dependency>
        <groupId>net.sourceforge.owlapi</groupId>
        <artifactId>owlapi-distribution</artifactId>
        <version>3.5.7</version>
</dependency>
```
Furthermore the stanford NLP dependency was also missing
```
<dependency>
    <groupId>edu.stanford.nlp</groupId>
    <artifactId>stanford-corenlp</artifactId>
    <version>1.3.4</version>
</dependency>
```
These two dependencies use really old versions of the libraries but then it can at least compile.

Best regards
Sven

**Comment by liweizhuo001** [comment]
Thank you very much. I have solved this problem to some extend. 

The following code is my instantiated code of **GMap_MELT_OWLAPI.java**.
```
package de.uni_mannheim.informatik.dws.melt.demomatcher;
import java.net.URL;
import java.util.ArrayList;
import java.util.Properties;
import org.semanticweb.owlapi.model.OWLOntology;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import Actions.GMap_D;
import de.uni_mannheim.informatik.dws.melt.matching_owlapi.MatcherYAAAOwlApi;
import de.uni_mannheim.informatik.dws.melt.yet_another_alignment_api.Alignment;
import de.uni_mannheim.informatik.dws.melt.yet_another_alignment_api.CorrespondenceRelation;

public class GMap_MELT_OWLAPI extends MatcherYAAAOwlApi {  
	private static final Logger LOGGER = LoggerFactory.getLogger(GMap_MELT_OWLAPI.class);
	public GMap_D gmap;
	public ArrayList<String> mappings;
		
	public Alignment match(URL source, URL target, Alignment inputAlignment, Properties properties) throws Exception 	
	{
		Alignment alignment = new Alignment();
		try {
			gmap  =new GMap_D();			
			gmap.init(source, target);
									
			LOGGER.info("Matching with GMap completed");
								
			URL url_alignment=gmap.returnAlignmentFile();
			
			mappings=gmap.GetAligenmt();
			
			for(String s:mappings)
			{
				System.out.println(s);
				String parts[]=s.split(",");
				
				alignment.add(parts[0],parts[1],Double.parseDouble(parts[3]),CorrespondenceRelation.EQUIVALENCE);				
			}
						
		}
		catch (Exception e){
			LOGGER.error("Error matching with GMap");
			LOGGER.error(e.getLocalizedMessage());
		}
		
		return alignment;
	}
	
	public Alignment match(OWLOntology source, OWLOntology target, Alignment inputAlignment, Properties p)
			throws Exception {
		Alignment alignment = new Alignment();
		
		try {						
			LOGGER.info("Matching with GMap completed");
			mappings=gmap.GetAligenmt();
			
			for(String s:mappings)
			{
				System.out.println(s);
				String parts[]=s.split(",");
				
				alignment.add(parts[0],parts[1],Double.parseDouble(parts[3]),CorrespondenceRelation.EQUIVALENCE);				
			}		
		}		
			catch (Exception e){
				LOGGER.error("Error matching with GMap");
				LOGGER.error(e.getLocalizedMessage());
			}		
		return alignment;	
	}
}
```


This file is my matcher tested result for MELT.
[systemAlignment.txt](https://github.com/dwslab/melt/files/7039455/systemAlignment.txt)

The next question is how to output the whole results (containing properites) of alignment between two conference ontologies? Because the presented results only contain mappings of class.

I guess there have two ways to achieve my goal:
1. There exist the code testing for whole results, simialr as 
```
GMap_MELT_OWLAPI classMatcher = new GMap_MELT_OWLAPI();
Map<String, IOntologyMatchingToolBridge> matchers = new HashMap<>();
matchers.put("Class Matcher", classMatcher);
ExecutionResultSet result = Executor.run(TrackRepository.Conference.V1.getTestCase("confof-sigkdd"), matchers);
```

2. I can directly package this modified maven project but I am not sure the below pom.xml is right.  The suffix name needs to be changed to ".xml"
[pom.txt](https://github.com/dwslab/melt/files/7039556/pom.txt)

I sincerely hope that you can tell me the right ways. Thank you very much.

**Comment by janothan** [comment]
Hi,

(1) you overwrote `match(URL source...)` and `match(OWLOntology source...)`.
Since you extend the `MatcherYAAAOwlApi`, it is sufficient to only implement `match(OWLOntology source...)`.
If you want to only overwrite `match(URL source...)`, just extend `MatcherURL`.

(2) We are not sure about this question. Your code in option 1 looks good. This will run the matcher on the `confof-sigkdd` test case. 
The `systemAlignment.rdf` generated by `EvaluatorCSV` contains the complete alignment (with properties). If the matcher only matches classes, you will find only classes in the `systemAlignment.rdf` file. Hence, missing properties in the system alignment are likely a problem of the matcher implementation. 
Your `pom.xml` also looks ok on first sight. Note that this POM will package a docker container for you (not a SEALS package). 

We hope this helps,
Jan & Sven

**Comment by liweizhuo001** [comment]
Thank you very much. I have successfully run My Matcher in my local maven project simpleSealsMatcher and simpleWebMatcher.

The corresponding test file is **EvaluateMatcher3.java** in **de.uni_mannheim.informatik.dws.melt.demomatcher** package in **simpleSealsMatcher**.

 The corresponding test file is **EvaluationExample3.java** in **de.uni_mannheim.informatik.dws.melt.demomatcher** package in **simpleWebMatcher**.


However, I can not package them by the comand line **mvn clean package** or **mvn clean install**.

For simpleWebMatcherG  (renamed), 
The linkage of google drive is: https://drive.google.com/file/d/1-t-Q0AmJ2wg5IaX9F00OLVuLI9Kw2hpX/view?usp=sharing
I have installed docker but the error messages are 
```
[ERROR] DOCKER> Unable to build image [gmap-1.0-web] : {"message":"dockerfile parse error line 6: unknown instruction: \"GMAP-1.0.JAR:LIB/*\""} (Bad Request: 400) [{"message":"dockerfile parse error line 6: unknown instruction: \"GMAP-1.0.JAR:LIB/*\""} (Bad Request: 400)]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:57 min
[INFO] Finished at: 2021-08-25T19:06:52+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.36.0:build (default) on project GMap: Unable to build image [gmap-1.0-web] : {"message":"dockerfile parse error line 6: unknown instruction: \"GMAP-1.0.JAR:LIB/*\""} (Bad Request: 400) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

For simpleSealsMatcher2021 (renamed), 
The linkage of google drive is: https://drive.google.com/file/d/1Eeki-S2mXFYjtzfQmXTn23Wf-nxqz_f8/view?usp=sharing

The error messages focus on the missing of my package.
```
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [6,1] the package edu.mit.jwi.item does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [7,1] the package edu.mit.jwi.data does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [12,1] the package edu.mit.jwi does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [13,1] the package edu.mit.jwi does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [14,1] the package edu.mit.jwi.data does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [15,1] the package edu.mit.jwi.data.compare does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [16,1] the package edu.mit.jwi.data.parse does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [17,1] the package edu.mit.jwi.item does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [18,1] the package edu.mit.jwi.morph does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [19,24] the package edu.mit.jwi.item does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [20,19] the package edu.mit.jwi does not exist
[error]/users/liweizhuo/eclipse-workspace-new/simplesealmatcher2021/src/main/Java/jws/jws.java: [37,17] no symbol found

```

I do not know how to solve above problems.

Can you help me or guide me how to solve above problems. Thank you very much.

**Comment by sven-h** [comment]
For the initial answer you had ( by now you figured out some parts already):

For the first part:

It looks like the pom file is automatically formatted.
This actually caused the error.
The problematic lines are between line 137 and 141:
```
<cmd>
    <shell>java -cp 
        "${project.build.finalName}.${project.packaging}:lib/*" 
        de.uni_mannheim.informatik.dws.melt.receiver_http.Main</shell>
</cmd>
```
You can solve it in two ways:
1) You put the shell command in one line like:
```
<cmd>
    <shell>java -cp "${project.build.finalName}.${project.packaging}:lib/*" de.uni_mannheim.informatik.dws.melt.receiver_http.Main</shell>
</cmd>
```
2) You add backslash at the end of each line to indicate that the line continues:
```
<cmd>
    <shell>java -cp \
        "${project.build.finalName}.${project.packaging}:lib/*" \
        de.uni_mannheim.informatik.dws.melt.receiver_http.Main</shell>
</cmd>
```

The the second part:
The compilation does not work because you missed two dependencies:
```
<dependency>
    <groupId>edu.mit</groupId>
    <artifactId>jwi</artifactId>
    <version>2.2.3</version>
</dependency>

<dependency>
    <groupId>net.sourceforge.owlapi</groupId>
    <artifactId>org.semanticweb.hermit</artifactId>
    <version>1.3.8.413</version>
</dependency>
```
The first dependency is also a dependency of `matching-eval` and thus it was not neccessary in the web packageing project (there the scope `test` was removed and thus the dependency was included).


Furthermore we would like to mention, that you do not necessarily have to adjust two projects at the same time.
You can also move the build plugins and dependencies into one project. Then both packages are created within this one project.
We attached a 
[working pom](https://github.com/dwslab/melt/files/7048210/pom.txt)  which shows this. In this pom, the `matching-eval` dependency is in scope `test` this means, 
that you should put your evaluation code in the maven `test` folder or remove the `scope` within the dependency to run the executor
in java classes located in `src/main/` folder. Furthermore the `matching-jena` can be removed if you remove also all example matchers from your project.

For the project covering both packagings you can call `mvn package` to only build the seals package or `mvn install` to build the seals and web/docker package.

**Comment by sven-h** [comment]
For the problem with the docker, can you please add the following lines when evaluating your web package?
```
Thread.sleep(20000); // just to be sure that all logs are written.
dockerMatcher.logAllLinesFromContainer();
```
Directly after `Executor.run`.

Such that it looks like:

```
// Let's run the matchers on the tracks:
ExecutionResultSet result = Executor.run(TrackRepository.Conference.V1, matchers);

Thread.sleep(20000); // just to be sure that all logs are written.
dockerMatcher.logAllLinesFromContainer();

// Step 3: Use your favorite evaluator to interpret the result.
//         The results are serialized in directory: "./results".
EvaluatorCSV evaluatorCSV = new EvaluatorCSV(result);
evaluatorCSV.writeToDirectory();
```

And send the full log file.
Thank you.

**Comment by sven-h** [comment]
Hi @liweizhuo001 ,

the easiest way is to install the jar file you have into your local repository.
I added a section about [installing third party jars in the FAQ of MELT](https://dwslab.github.io/melt/faq#install-jar-file-locally-which-is-not-in-maven-central).
Please have a look there and let me know if it is easy to understand and works in your case.

The command to install your jar file would be:
```
mvn install:install-file -Dfile=stanford-postagger.jar -DgroupId=edu.stanford.nlp -DartifactId=stanford-postagger -Dversion=1.0 -Dpackaging=jar`
```
and the jar file needs to be located in the same folder where you execute the command (or change the path to the file).

You can then depend in your project on this file with
```
<dependency>
    <groupId>edu.stanford.nlp</groupId>
    <artifactId>stanford-postagger</artifactId>
    <version>1.0</version>
</dependency>
```

Best regards
Sven

**Comment by liweizhuo001** [comment]
Thank you very much. I have solved it.  

For the maven project **simpleWebMatcher**,

1. Enter the directory of src/main/resources by comand line.
2. command to install the **stanford-postagger.jar** file
`mvn install:install-file -Dfile=stanford-postagger.jar -DgroupId=pos-tagger -DartifactId=stanford-pos-tagger -Dversion=3.0.2 -Dpackaging=jar`
3. Then add the follow depency in the pom.xml
 ```
       <dependency>  
   		 <groupId>pos-tagger</groupId>  
    		 <artifactId>stanford-pos-tagger</artifactId>  
   		 <version>3.0.2</version>  
       </dependency> 
```
4. Return the root directory of the maven project by command line. Then, input **maven clean install**. The expected package can be generated, and I can test my Macther with complete functions :-)

I suggest that you can select some concrete problems and transform them into the introdcution in Matcher Packaging in [Melt](https://dwslab.github.io/melt/matcher-packaging).  It can lower the threshold for participants of OAEI to utilize MELT platform, and make much more researchers join in the community of the ontology matching.
