### ISSUE TITLE
Make the new biodiv dataset available in the MELT repository

### ISSUE THREAD

**Issue by sven-h** [dwslab/melt#130]
The new biodiv track is available on the webiste but not yet in the MELT repository.

**Comment by naouelkaram** [comment]
The link to the ontologies/thesauri: https://owncloud.fokus.fraunhofer.de/index.php/s/MDbYP4KvylHXusQ/download

**Comment by naouelkaram** [comment]
I will share an additional link with the OWL versions of the thesauri (the original ones are SKOS)

**Comment by sven-h** [comment]
I uploaded it now. It is also available in the [track repository](https://dwslab.github.io/melt/track-repository#available-tracks).
If you use the evaluation client, please specify the full track via 
```
-track http://oaei.webdatacommons.org/tdrs/ biodiv 2021
```
If everything is fine, we can make this version also the default in the evaluation client.

What I noticed during uploading:
- agrovoc-nalt
  - I changed the source and target
- envo-sweet
   - the target ontology uses always the namespace `http://www.cropontology.org` while in the reference there is `http://sweetontology.net`

The other two I didn't checked in detail.
Maybe you can have a look again and let me know if I should change something.

If everything is fine with this version, I will also upload the OWL version with a different version tag.

Best regards
Sven

**Comment by naouelkaram** [comment]
Thanks for pointing that out Sven, here is the right SWEET version: https://owncloud.fokus.fraunhofer.de/index.php/s/Mw4t7ZaWe3AhTHp/download

**Comment by sven-h** [comment]
Hi,

I have updaed the SWEET ontology as already mentioned in a mail.

I run further tests to see if the reference entities appear in the parsed ontologies ( with melt-validation project).
You find the resultd in the following zip file:
[biodiv_2021.zip](https://github.com/dwslab/melt/files/7252941/biodiv_2021.zip)

The important parts are 
- column "Entities not found" in aggreated.csv
- further information can be found in each file

Following the important parts:

| Test case| Jena | OWLAPI |
|---|---|---|
| agrovoc-nalt| :x:  | :white_check_mark: (93 source entities could not be found) |
| envo-sweet | :white_check_mark: (16 source entities could not be found) | :white_check_mark: (16 source entities could not be found) |
| gemet-anaee| :x: (see below) | :white_check_mark: |
| ncbi-taxrefld | :x: | :x:|

What I found out e.g. for test case `gemet-anaee` is that jena is not detecting the resources as instances and thus they will not be retrieved by methods like `listIndividuals`.

If I add
```
<rdf:Description rdf:about="http://www.w3.org/2004/02/skos/core#Concept">
    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
</rdf:Description>
```
to the ontologies, then this test case also works fine for jena based matchers.

Maybe you can have a closer look and let me know if I should make these changes.

Best regards
Sven

**Comment by naouelkaram** [comment]
Dear Sven,
thanks for the update. I suggest we run the evaluation on the OWL versions, I checked the files and uploaded them again here: https://owncloud.fokus.fraunhofer.de/index.php/s/IyGdqZVzqn4LBfe
Could you upload it for us with a different version tag?
Many thanks and best regards,
Naouel

**Comment by naouelkaram** [comment]
Many thanks Sven, the issue with ncbi-taxrefld is not the URIs in the reference, I double checked. It is probably due to the large size of the ontologies, we need to find a solution for this task as for now, none of the systems can deal with it.
We will let you know when we are finished with the evaluation to discard the erroneous versions.

Best regards,
Naouel
