### ISSUE TITLE
Enable disabled Test

### ISSUE THREAD

**Issue by sven-h** [dwslab/melt#178]
Part of a Wikidata test is disabled

**Comment by sven-h** [comment]
1. WikidataKnowledgeSourceTest.java -> isHypernym method disabled
1. KGvec2goClientTest -> full class

**Comment by janothan** [comment]
Wikidata fix: [c9b9c1a](https://github.com/dwslab/melt/commit/c9b9c1a34b90acc89b26ef07534e32f69eb2604b) 
KGvec2go fix: [9d317dc](https://github.com/dwslab/melt/commit/9d317dc6b05bbd289ed03cd4d07a1251e5f998af)
