### ISSUE TITLE
Could not determine resource type neither from source nor target

### ISSUE THREAD

**Issue by abhiseksharma** [dwslab/melt#185]
Hi,

Getting the following message while running logmap's docker image over local track:

WARN  TypeRefiner               - Could not determine resource type neither from source nor target: <http://cmt_de#c-7221579-7498183,http://cmt_hi#c-3010445-5735707,0.0,=> (Source Ontology: ; Target Ontology: ). Ignore it silently. Have a look at the Alignment - some URIs might be wrong and do not appear in the ontology or the reasoner is not expressive enough.

Please help me decipher this.

Abhisek

**Comment by sven-h** [comment]
Hi Abhisek,

if you just interested in the alignment file, this is not a problem.
When evaluating with the MELT evaluators, then it means that the partitioning into class, property, and instance correspondences does not work for this correspondence. The "overall" measures should still be correct.

Best regards
Sven

**Comment by sven-h** [comment]
In addition: maybe check if the resources are actaully present in the ontology files

**Comment by sven-h** [comment]
In case this issue is solved for you, can you please close it?

**Comment by abhiseksharma** [comment]
Yes, it is solved thank you. 
Somehow the order of source and target ontology in context with reference alignment file was the issue. After correcting it the issue got resolved, though still getting 0 correspondences. 

Thanks,
Abhisek
