### ISSUE TITLE
Link to Command Line Tool Download not Working

### ISSUE THREAD

**Issue by janothan** [dwslab/melt#213]
### Describe the bug
Minor observation: In the markdown documentation, the link to the CL Tool is not working: https://dwslab.github.io/melt/matcher-evaluation/client

**Comment by sven-h** [comment]
Do you mean the link for downloading the evaluation client?
https://nightly.link/dwslab/melt/workflows/java_client_upload/master/evaluation-client.zip

This link works for me.

**Comment by sven-h** [comment]
closing as the link works
