### ISSUE TITLE
[Question] Is kgvec2go.org down?

### ISSUE THREAD

**Issue by rami3l** [dwslab/melt#219]
Thanks a lot for making this project!

I am currently working on a project that is based on your `kgvec2go` service, which has been working great for me.

I don't know if this is the right place to ask (sorry if this is not the case), but it seems to me that when I try to access www.kgvec2go.org I'm always getting an `ERR_CONNECTION_TIMED_OUT` from my browser.
At the time of writing, the latest Google snapshot was made at 10:59:16 GMT, Sep 5, 2023.

Would you mind having a look? Many thanks! 🙏

PS: Is this related to #215?

**Comment by sven-h** [comment]
Hi,

there is also the [kgvec2go github repository](https://github.com/janothan/kgvec2go-server) which is probably a better place.
The service was created by Jan who is not working in research anymore.
We are currently checking how we can continue running the servers.

Best regards
Sven
