### ISSUE TITLE
Cannot run RDF2VecMatcher in example

### ISSUE THREAD

**Issue by 1210768015** [dwslab/melt#220]
Hello, I can't run this RDF2VecMatcher example.
![image](https://github.com/dwslab/melt/assets/66861694/f339559f-bdc5-4bdf-93c8-ab21def956ca)

**Comment by sven-h** [comment]
Hi,

if you want to generate rdf2vec embeddings without using it for ontology matching, you can also use [jrdf2vec](https://github.com/dwslab/jRDF2Vec) directly.

If you want to use it for ontology matching, can you provide the full log file?
 
Best regards
Sven

**Comment by 1210768015** [comment]
Thank you very much for your reply. This is my log file
[log.txt](https://github.com/dwslab/melt/files/13194642/log.txt)

**Comment by sven-h** [comment]
Hi,

sorry for the delay.
I saw that the example is quite outdated (not all examples are updated with the framework as well).
Thus, I changed a few lines in the last commit [04f7e48](https://github.com/dwslab/melt/commit/04f7e48532e8ea809694e25a2f431a1a21dfa2ef).
Can you try running it now?
You probably need to install the SNAPSHOT version of MELT by running
```
mvn install -DskipTests -Dmaven.javadoc.skip=true
```
in the main folder (see also the [installation guide](https://dwslab.github.io/melt/installation))
