### ISSUE TITLE
Build of MELT fails

### ISSUE THREAD

**Issue by FelixFrizzy** [dwslab/melt#221]
### Describe the bug
I tried to build MELT but it fails on the Machine Learning Module. Priority is low from my side, I dont need the failed ML module right now. 

### To Reproduce

- Version of MELT: current master branch with commit hash 963bc647a13c52d75545839d846a63f3f8d5c304
- Java version: java version "15" 2020-09-15 (Java(TM) SE Runtime Environment (build 15+36-1562))
- Python version: 3.12.3
- Operating system: macos 14.4

#### Full log output

see attachment
[log.log](https://github.com/dwslab/melt/files/15467926/log.log)

### Expected behavior
I expect that the build succeeds ;-)

**Comment by FelixFrizzy** [comment]
The build does not fail because of a missing dependency like written in #222, because I still have this dependency in the cache on this system (but not on the system in #222).

**Comment by FelixFrizzy** [comment]
I just deleted the local maven repo and tried everything again. Now it works. I suspect that somewhere between Dec 2023 and march 2024, something that was broken ended up in the local repo and didnt get replaced. So this issue can be closed

**Comment by sven-h** [comment]
Is it still the same error?

**Comment by FelixFrizzy** [comment]
I tried again and it worked after I deleted the ~/.m2 folder (=local maven repository). So this is resolved
