### ISSUE TITLE
Residual True Positive Matcher

### ISSUE THREAD

**Issue by sven-h** [dwslab/melt#25]
Problem: Trivial matches are not marked as residual TP.
Reason: The baseline matcher matches "the first label". The matcher needs to be refactored to match ALL trivial matches - not just the first one.

**Comment by janothan** [comment]
You can set the true positive matcher using `public void setBaselineMatcher(IOntologyMatchingToolBridge baselineMatcher)` of `EvaluatorCSV` in order to change the default baseline matcher. 

Thereby, you can set track-specific baselines and correctly calculate residual true positives.
