### ISSUE TITLE
Activation of maven-gpg-plugin for Release to Central

### ISSUE THREAD

**Issue by janothan** [dwslab/melt#34]
Currently, the profile for the gpg plugin cannot be activated. It is, therefore, copied into the plugin section and then removed again for every release resulting in various commits without any real changes. This works but is a bit dirty.

In the future it could be evaluated how to solve this issue elegantly, i.e. evaluate how the profile can be activated.

**Comment by sven-h** [comment]
Call `mvn ... -P release-profile` to actiavte the gpg plugin

**Comment by sven-h** [comment]
Did not work during last release

**Comment by janothan** [comment]
The issue has been resolved. 
The process is documented in the [user guide](https://dwslab.github.io/melt/contribute/project-management)
