### ISSUE TITLE
Move some methods of BaselineStringMatcher to some util class

### ISSUE THREAD

**Issue by ychmi** [dwslab/melt#43]
`BaselineStringMatcher` features the `normalize(String stringToBeNormalized)` and `getLabelOrFragment(OntResource resource)` methods, which I find extremely useful for any matcher. Currently, I use these functions in my matchers by accessing them through `BaselineStringMatcher`, however I think it makes more sense to have these in one of the `util` classes.

**Comment by janothan** [comment]
Thank you for bringing up this enhancement request. The latest MELT release on mvn central addresses this issue: We have introduced multiple [`LiteralExtractor`s](https://dwslab.github.io/melt/matcher-development/matching-with-jena#literalextractors) which can be used to obtain textual representations.
